services:
  orbit_ctgov_data_builder:
    platform: linux/amd64
    build: .
    image: orbit:latest
    container_name: orbit_ctgov_data_builder
    environment:
      MODE: ctgov
      ORBIT_CTGOV_INDEX_PATH: /app/index-ctgov
      ORBIT_CTGOV_BASELINE_PATH: /app/baseline-ctgov
    volumes:
      - ./index-ctgov:/app/index-ctgov
      - ./baseline-ctgov:/app/baseline-ctgov
    restart: on-failure

  orbit_api:
    platform: linux/amd64
    build: .
    image: orbit:latest
    container_name: orbit_api
    environment:
      MODE: api
      ORBIT_CTGOV_INDEX_PATH: /app/index-ctgov
      ORBIT_CTGOV_SERVICE: 1
    depends_on:
      orbit_ctgov_data_builder:
        condition: service_completed_successfully
    ports:
      - "${ORBIT_PORT:-8333}:8000"
    volumes:
      - ./index-ctgov:/app/index-ctgov
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ORBIT_PORT}/docs"]
      interval: 30s
      timeout: 10s
      retries: 3           
    restart: always
