services:
  orbit_pubmed_data_builder:
    platform: linux/amd64
    build: .
    image: orbit:latest
    container_name: orbit_pubmed_data_builder
    environment:
      MODE: pubmed
      ORBIT_PUBMED_INDEX_PATH: index-pubmed
      ORBIT_PUBMED_BASELINE_PATH: baseline-pubmed
    volumes:
      - ./index-pubmed:/app/index-pubmed
      - ./baseline-pubmed:/app/baseline-pubmed
    exclude_from_hc: true      
    restart: on-failure

  orbit_api:
    platform: linux/amd64
    build: .
    image: orbit:latest
    container_name: orbit_api
    environment:
      MODE: api
      ORBIT_PUBMED_INDEX_PATH: /app/index-pubmed
      ORBIT_PUBMED_SERVICE: 1
    depends_on:
      orbit_pubmed_data_builder:
        condition: service_completed_successfully
    ports:
      - "${ORBIT_PORT:-8333}:8000"
    volumes:
      - ./index-pubmed:/app/index-pubmed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ORBIT_PORT}/docs"]
      interval: 30s
      timeout: 10s
      retries: 3           
    restart: always
