FROM openpm-data:latest

WORKDIR /api
COPY ./main.py ./.venv ./pyproject.toml ./uv.lock /api
RUN uv sync
RUN uv sync --frozen --no-cache
RUN uv add fastapi --extra standard
RUN uv run -m pip install /pybool_ir/pylucene/dist/*.whl
RUN uv run -m pip install -e /pybool_ir
EXPOSE 3000

ENTRYPOINT [ "uv", "run", "-m", "fastapi", "dev", "main.py" ]
