FROM ghcr.io/hscells/pybool_ir:master

WORKDIR /app
COPY main.py pyproject.toml uv.lock /app/
RUN pip install uv
RUN uv sync
RUN uv run -m pybool_ir.cli pubmed download -b baseline
RUN uv run -m pybool_ir.cli pubmed process -b baseline -o pubmed-processed.jsonl
RUN rm -rf baseline
RUN uv run -m pybool_ir.cli pubmed index -b pubmed-processed.jsonl -s 1 -i index
RUN rm pubmed-processed.jsonl