services:
  data_builder:
    platform: linux/amd64
    build: .
    image: openpm:latest
    container_name: openpm_data_builder
    environment:
      MODE: full
      DOWNLOAD_TARGET: baseline
    volumes:
      - ${INDEX_PATH:-./index}:/app/index
      - ${BASELINE_PATH:-./baseline}:/app/baseline
    restart: always

  api:
    platform: linux/amd64
    build: .
    image: openpm:latest
    container_name: openpm_api
    environment:
      MODE: api
    depends_on:
      data_builder:
        condition: service_completed_successfully
    ports:
      - "${OPENPM_PORT:-8333}:8000"
    volumes:
      - ${INDEX_PATH:-./index}:/app/index
    restart: always
