version: '3.8'

services:
  data_builder: 
  build:
    context: .
    dockerfile: Dockerfile.data
    args:
      PLATFORM: linux/amd64

    image: openpm-data:latest

    container_name: openpm_data_builder

    volumes:
      - ./app:/app/

    restart: 'no'

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
      args:
         PLATFORM: linux/amd64

      container_name: openpm_api
      image: openpm_api:latest

      depends_on:
        - data_builder

      ports: 
        - "8000:3000"

      volumes: 
      - ./app:/app/

      restart: always