# TODO Test skript -> check if this works
services:
  data_builder:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.data
      args:
        PLATFORM: linux/amd64
    image: openpm-data:latest
    container_name: openpm_data_builder
    environment:
      - MODE=test
      - DOWNLOAD_TARGET=baseline
    volumes:
      - ./app:/app/
      - ./index:/app/index
    restart: 'no'

  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        PLATFORM: linux/amd64
    image: openpm_api:latest
    container_name: openpm_api
    depends_on:
      - data_builder
    ports:
        - "8000:8000"  # check mapping for 8000:3000

    environment:
      - PYTHONPATH=/api
    volumes:
      - ./:/api
    restart: always
